// Authoring helper only. Generated pages are plain, crawlable HTML; no build is required to host dist/.
import { mkdir, writeFile } from 'node:fs/promises';
const origin = 'https://padlab.m-usmanaslam18101999.workers.dev';
const pages = [
{path:'guides/stick-drift-test.html',title:'Stick Drift Test: Understand Joystick Offset & Deadzones',description:'Learn how to test joystick drift, interpret mean and peak analog stick offset, and compare resting movement with your game’s deadzone.',body:`
<div class="eyebrow">PADLAB FIELD GUIDE · ANALOG STICKS</div><h1>Stick drift, deadzones & the center point</h1><p class="article-meta">By PadLab · Updated October 5, 2026 · 4 minute read</p>
<p class="lead">When your character walks or your camera turns without a touch, the controller may be reporting movement at rest. A stick drift test helps you see that signal before changing settings.</p>
<h2>Run a repeatable joystick drift test</h2><ol><li>Connect your controller, open the <a href="/#tester">gamepad tester</a> and press a button. Confirm that the controller has a standard mapping.</li><li>Move both thumbsticks around their full range. Release them gently and place the controller on a steady surface.</li><li>Choose <strong>Run drift test</strong>. Keep the sticks untouched and the page visible during the three-second sample.</li><li>Compare mean and peak offset, then repeat after moving and releasing the sticks from another direction.</li><li>Export the report if you want a record. Use the same connection and browser when comparing later tests.</li></ol>
<h2>What the numbers mean</h2><p>Each axis reports a normalized position from −1 to +1. For a standard controller, X represents horizontal movement and Y represents vertical movement. The center is approximately zero. A rightward movement usually makes X positive; downward movement usually makes Y positive.</p><p>PadLab calculates radial offset as <code>sqrt(X² + Y²)</code>. An X value of 0.03 with Y at 0.04 gives a radial offset of 0.05, shown as 5%. A diagonal can exceed 100% when both axis values approach their limits. That alone is not a defect.</p><table><thead><tr><th>Measurement</th><th>What it tells you</th></tr></thead><tbody><tr><td>Current offset</td><td>Distance from the center in the latest browser reading.</td></tr><tr><td>Mean radial offset</td><td>Average distance from center across the sample. Opposing movements do not cancel out.</td></tr><tr><td>Peak radial offset</td><td>The largest distance observed during the sample.</td></tr><tr><td>Mean X and Y</td><td>The average direction of the center offset, included in the export.</td></tr></tbody></table>
<h2>Deadzone versus stick drift</h2><p>A deadzone is a region where a game ignores small movements. It can hide a center offset, but it also changes how soon aiming or steering responds. A game's radial or axial deadzone may behave differently from the reference circle in this tester.</p><p>The shaded circle in PadLab is a visual guide. Moving the slider does not filter the raw numbers, repair drift or change firmware. There is no universal acceptable offset: evaluate the reading against your game’s settings and the behavior you actually experience.</p>
<h2>What if the stick does not return to center?</h2><p>Repeat the check with a USB data connection and verify that no remapping utility is adding a virtual controller. Check the manufacturer's documentation for supported firmware updates and calibration. If the same unwanted movement persists across games and devices, seek manufacturer support or a qualified repair service.</p><p>Hall effect and TMR describe sensing technologies. They do not guarantee a perfectly centered reading; springs, mechanics, firmware and calibration still affect the reported position.</p>
<div class="callout"><strong>Testing is not hardware calibration.</strong><p>This tool observes values the browser exposes. It cannot access every sensor reading, certify a controller’s condition, or rewrite calibration data.</p></div>
<h2>About the measurement</h2><p>The sample lasts at least three seconds in a visible tab and collects readings at the interface’s refresh cadence. Repeated frames may contain the same hardware value. Results describe that sample, not USB polling frequency, long-term reliability or end-to-end input lag.</p><p>Technical reference: <a href="https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API">MDN’s Gamepad API guide</a>. Also read our <a href="/guides/controller-button-test.html">button and trigger test routine</a>.</p>`},
{path:'guides/controller-button-test.html',title:'Controller Button Test: Buttons, D-pad & Analog Triggers',description:'Test gamepad buttons, D-pad directions, bumpers and analog trigger travel. Understand standard mappings, pressed states and values from 0 to 1.',body:`
<div class="eyebrow">PADLAB FIELD GUIDE · BUTTONS & TRIGGERS</div><h1>Is every button doing its job?</h1><p class="article-meta">By PadLab · Updated October 5, 2026 · 3 minute read</p><p class="lead">A controller button test makes missing or stuck inputs easier to spot. Work through each control individually so you can connect a physical press with its on-screen reading.</p>
<h2>A complete button check</h2><ol><li>Open the <a href="/#tester">controller tester</a> and connect your gamepad.</li><li>Press each face button slowly and release it. The corresponding cell should show a pressed state and then return to its released value.</li><li>Test all four D-pad directions, both shoulder bumpers, the menu controls and each thumbstick click.</li><li>Press combinations you use in games. Watch the individual cells while holding and releasing them.</li><li>Review the session’s observed-button count. A marked cell means a press was observed, not that the button passed a durability test.</li></ol>
<h2>Xbox and PlayStation button equivalents</h2><p>The standard mapping describes control positions rather than printed symbols. PadLab uses Xbox-style diagram labels and lists PlayStation equivalents in the input cells.</p><table><thead><tr><th>Position</th><th>Xbox</th><th>PlayStation</th><th>Standard index</th></tr></thead><tbody><tr><td>Bottom face button</td><td>A</td><td>Cross</td><td>0</td></tr><tr><td>Right face button</td><td>B</td><td>Circle</td><td>1</td></tr><tr><td>Left face button</td><td>X</td><td>Square</td><td>2</td></tr><tr><td>Top face button</td><td>Y</td><td>Triangle</td><td>3</td></tr><tr><td>Left / right bumper</td><td>LB / RB</td><td>L1 / R1</td><td>4 / 5</td></tr><tr><td>Left / right trigger</td><td>LT / RT</td><td>L2 / R2</td><td>6 / 7</td></tr></tbody></table>
<p>Nintendo face-button lettering differs. For unmapped gamepads, follow numbered buttons and raw axes instead of assuming the standard layout. Extra controls such as touchpads or paddles appear only if the browser exposes them; some duplicate existing inputs.</p>
<h2>Test analog trigger travel</h2><p>Squeeze each trigger gradually. On a standard analog trigger, its value should generally rise from near 0 toward 1, then return when released. Watch for an unexpected jump or a value that stays raised. Some controllers and modes expose triggers as digital buttons, so only two values may be available.</p><p>The browser supplies both a numeric value and a pressed flag. A partly squeezed trigger can have a nonzero value before the pressed flag becomes true. PadLab displays both concepts rather than treating every nonzero value as a completed press.</p>
<h2>Check vibration separately</h2><p>If the browser exposes a compatible vibration actuator, <strong>Test vibration</strong> sends a half-second dual-rumble command. Confirm the physical response yourself. A completed software command is not proof that both motors are healthy, and standard rumble is not a test of DualSense adaptive triggers or every advanced haptic feature.</p>
<h2>Understand the limits</h2><p>A browser can miss very brief transitions between sampled frames. This is not a switch-debounce analyzer or a latency benchmark. If a button behaves differently in a game, check that game's bindings, controller profiles and accessibility settings. For connection problems, use our <a href="/guides/controller-not-detected.html">detection troubleshooting guide</a>.</p><p>Reference: <a href="https://developer.mozilla.org/en-US/docs/Web/API/GamepadHapticActuator/playEffect">MDN: vibration effects and support</a>.</p>`},
{path:'guides/controller-not-detected.html',title:'Controller Not Detected? USB, Bluetooth & Browser Checks',description:'Troubleshoot a gamepad that is connected but not detected in a browser. Check USB data cables, Bluetooth pairing, browser access and controller mapping.',body:`
<div class="eyebrow">PADLAB FIELD GUIDE · CONNECTIONS</div><h1>Connected, but not detected?</h1><p class="article-meta">By PadLab · Updated October 5, 2026 · 3 minute read</p><p class="lead">A controller can be paired with your computer without being visible to a web page. Start with the connection, then check how the browser exposes gamepad input.</p>
<h2>1. Activate the controller on the page</h2><p>Open the <a href="/#tester">gamepad tester</a>, keep its tab visible and press a physical controller button. Some browsers wait for controller interaction before exposing a device. Clicking the page alone may not activate gamepad detection.</p>
<h2>2. Check the USB connection</h2><p>Use a cable that supports data, not only charging. Try a direct USB port and another known working data cable. A charging light shows that the controller receives power; it does not confirm that inputs are reaching the operating system.</p>
<h2>3. Check Bluetooth pairing</h2><p>Verify that the controller is connected in your operating system’s Bluetooth settings and has enough charge. Follow the manufacturer's pairing instructions for the exact model. A device may reconnect to a console or another computer instead. Compare with USB if you need to isolate the wireless connection.</p>
<h2>4. Open the tester directly in a supported browser</h2><p>Use a current browser that supports the Gamepad API. Open the tester over HTTPS as a normal page. Embedded frames and browser policies can restrict controller access. If the page reports that the API is unavailable or blocked, try another browser and check any relevant managed-device policies.</p>
<h2>5. Inspect controller mode and remapping software</h2><p>Some PC controllers offer XInput, DirectInput or console-specific modes. Those modes may change how the operating system recognizes the device. Follow the controller documentation rather than changing modes at random. Steam Input and other remappers can expose virtual controllers; select the intended device in the tester’s controller menu.</p>
<h2>6. Separate detection from mapping</h2><p>If button numbers and axis values appear, detection is working. A missing standard mapping means the browser has not assigned familiar control positions. PadLab keeps the raw data available and disables the standard stick interpretation. It does not assume that axis 0 is a thumbstick on every wheel, flight stick or unusual gamepad.</p>
<h2>7. Compare another application or device</h2><p>Check whether the controller works in an operating-system controller panel or a known compatible game. If it fails across applications, follow the manufacturer's driver and firmware instructions. If it works elsewhere, record the controller model, operating system, browser version and connection type to narrow down the compatibility issue.</p>
<div class="callout"><strong>Detected does not mean every feature is exposed.</strong><p>A browser may receive buttons and axes while omitting vibration, a touchpad, a microphone or a battery reading. PadLab does not claim to test features it cannot access.</p></div><p>Once inputs appear, follow the <a href="/guides/controller-button-test.html">button test</a> or <a href="/guides/stick-drift-test.html">stick drift test</a>. Technical reference: <a href="https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API">MDN’s Gamepad API guide</a>.</p>`},
{path:'about.html',title:'About PadLab & Our Controller Testing Methodology',description:'How PadLab measures controller inputs, what its drift test reports, and the limits of browser-based gamepad diagnostics.',body:`<div class="eyebrow">ABOUT THE TOOL</div><h1>Know what you’re measuring.</h1><p class="lead">PadLab is an independent, free browser tool for observing gamepad inputs. It helps you investigate a controller’s behavior without installing a diagnostic application.</p><h2>Our testing method</h2><p>The tester reads currently exposed devices with the Gamepad API. The interface updates at approximately 30 frames per second while the page is visible. Button coverage records which pressed states were observed during the selected controller’s session. A three-second drift sample reports average and peak radial distance from center, as well as directional averages in the exported JSON.</p><h2>What we do not measure</h2><p>PadLab does not measure true input latency, USB polling frequency, electrical switch quality, microphone performance or battery health. It does not rewrite hardware calibration. Its visual deadzone never alters raw readings or your controller settings.</p><h2>Compatibility and interpretation</h2><p>Standard browser mappings enable the controller illustration and stick pairs. Unmapped devices retain numbered input feedback. Vibration is available only when a supported actuator is exposed. Results depend on the operating system, browser, controller firmware and connection.</p><h2>Editorial approach</h2><p>Our guides explain the tool’s actual behavior and link to technical references. No brand endorsements, device certifications or physical laboratory tests are implied. PadLab is not affiliated with Microsoft, Sony, Nintendo or other controller manufacturers.</p><h2>Sources</h2><p><a href="https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API">MDN: Using the Gamepad API</a><br><a href="https://developer.mozilla.org/en-US/docs/Web/API/GamepadHapticActuator/playEffect">MDN: Gamepad vibration effects</a></p>`},
{path:'privacy.html',title:'Privacy — PadLab Gamepad Tester',description:'PadLab processes controller input locally in your browser. Learn what session data is used and what happens when you export a report.',body:`<div class="eyebrow">PRIVACY</div><h1>Your inputs stay with you.</h1><p class="article-meta">Updated October 5, 2026</p><p class="lead">The PadLab tester reads controller inputs locally. Its application code does not send your controller ID, button activity, axis values or test results to a server.</p><h2>Session data</h2><p>Controller readings, observed buttons and drift samples are held in page memory. Reset clears the current button coverage and drift results; ongoing inputs can immediately add new observations. Reloading or closing the page discards the session. Switching controllers starts a fresh session.</p><h2>Downloads</h2><p>Export results creates a JSON file in your browser. The file includes the browser-reported controller ID, input snapshot, test measurements and export time. You control whether to share that file.</p><h2>Cookies and hosting</h2><p>The tester’s application code sets no cookies, uses no local storage, and includes no analytics or advertising scripts. The hosting platform may process ordinary request logs or use authentication cookies for a private preview. Those platform functions are separate from local controller testing.</p><h2>External links</h2><p>Guides link to technical documentation. Visiting those sites is subject to their own policies.</p>`}
];
for (const page of pages) {
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${page.title} | PadLab</title><meta name="description" content="${page.description}"><link rel="canonical" href="${origin}/${page.path}"><meta property="og:title" content="${page.title}"><meta property="og:description" content="${page.description}"><meta property="og:type" content="${page.path.startsWith('guides/') ? 'article' : 'website'}"><meta property="og:url" content="${origin}/${page.path}"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/styles.css"></head><body><a class="skip" href="#content">Skip to content</a><header class="site-header"><div class="container nav"><a class="brand" href="/"><img src="/assets/favicon.svg" width="34" height="34" alt="">padlab<span class="brand-dot">.</span></a><nav aria-label="Main navigation"><a href="/#tester">Gamepad tester</a><a href="/#guides">Guides</a></nav><span class="privacy-pill">Local. Private. Free.</span></div></header><main id="content" class="container article"><a href="/">← Back to gamepad tester</a>${page.body}<p><a class="button primary" href="/#tester">Test your controller →</a></p></main><footer class="container footer"><a class="brand" href="/">padlab.</a><nav aria-label="Footer"><a href="/about.html">About & methodology</a><a href="/privacy.html">Privacy</a><a href="/#guides">Guides</a></nav><small>© 2026 PadLab. Independent controller diagnostics.</small></footer></body></html>`;
  await mkdir('dist/' + page.path.split('/').slice(0,-1).join('/'), { recursive:true });
  await writeFile('dist/' + page.path, html);
}
await writeFile('dist/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['', ...pages.map(p => p.path)].map(p => `<url><loc>${origin}/${p}</loc></url>`).join('')}</urlset>\n`);
await writeFile('dist/robots.txt', `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Generated ${pages.length} content pages and crawl files.`);
